apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0
  namespace: core-supply-com
spec:
  selector:
    matchLabels:
      app: peer0
  template:
    metadata:
      labels:
        app: peer0
    spec:
      containers:
      - name: peer0
        image: hyperledger/fabric-peer:amd64-2.2.0
        env:
          # - name: CORE_VM_ENDPOINT
          #   value: "unix:///host/var/run/docker.sock"
          - name: CORE_VM_ENDPOINT
            value: http://dind.core-supply-com:2375
          - name: FABRIC_LOGGING_SPEC
            value: "DEBUG"
          - name: CORE_PEER_TLS_ENABLED
            value: "true"
          - name: CORE_PEER_GOSSIP_USELEADERELECTION
            value: "true"
          - name: CORE_PEER_GOSSIP_ORGLEADER
            value: "false"
          - name: CORE_PEER_PROFILE_ENABLED
            value: "true"
          - name: CORE_PEER_TLS_CERT_FILE
            value: "/etc/hyperledger/fabric/tls/server.crt"
          - name: CORE_PEER_TLS_KEY_FILE
            value: "/etc/hyperledger/fabric/tls/server.key"
          - name: CORE_PEER_TLS_ROOTCERT_FILE
            value: "/etc/hyperledger/fabric/tls/ca.crt"
          - name: CORE_PEER_TLS_SERVERHOSTOVERRIDE
            value: peer0.core.supply.com
          - name: CORE_PEER_ID
            value: peer0.core.supply.com
          - name: CORE_PEER_ADDRESS
            value: peer0.core.supply.com:7051
          - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
            value: peer0.core.supply.com:7051
          - name: CORE_PEER_LOCALMSPID
            value: "GylCoreOrg1MSP"
          - name: CORE_PEER_ADDRESSAUTODETECT
            value: "true"
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command:
          - peer
          - node
          - start
        volumeMounts:
          - name: timezone
            mountPath: /etc/localtime
          - name: log
            mountPath: /var/log
          - name: run
            mountPath: /host/var/run/
          - name: fabric-pvc
            mountPath: /var/hyperledger/production
            subPath: gyl/gyl_core_org1/data/peer0
          - name: fabric-pvc
            mountPath: /etc/hyperledger/fabric/msp
            subPath: gyl/gyl_core_org1/cert/peerOrganizations/core.supply.com/peers/peer0.core.supply.com/msp
          - name: fabric-pvc
            mountPath: /etc/hyperledger/fabric/tls
            subPath: gyl/gyl_core_org1/cert/peerOrganizations/core.supply.com/peers/peer0.core.supply.com/tls
          - name: ebl-core
            mountPath: /etc/hyperledger/fabric/core.yaml
            subPath: core.yaml
          - name: ebl-detect
            mountPath: /builders/external/bin/detect
            subPath: detect
          - name: ebl-build
            mountPath: /builders/external/bin/build
            subPath: build
          - name: ebl-release
            mountPath: /builders/external/bin/release
            subPath: release
          # - name: fabric-pvc
          #   mountPath: /etc/hyperledger/fabric/channel_block
          #   subPath: gyl/gly_core_org1/channel_block
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
            type: ""
        - name: log
          hostPath:
            path: /var/log
            type: ""
        - name: run
          hostPath:
            path: /var/run
        - name: fabric-pvc
          persistentVolumeClaim:
            claimName: fabric-pvc
        - name: ebl-core
          configMap:
            name: ebl-config
            items:
              - key: core.yaml
                path: core.yaml
        - name: ebl-detect
          configMap:
            name: ebl-config
            items:
              - key: detect
                path: detect
                mode: 0544
        - name: ebl-build
          configMap:
            name: ebl-config
            items:
              - key: build
                path: build
                mode: 0544
        - name: ebl-release
          configMap:
            name: ebl-config
            items:
              - key: release
                path: release
                mode: 0544
---
apiVersion: v1
kind: Service
metadata:
   namespace: core-supply-com
   name: peer0
spec:
 selector:
   app: peer0
 type: ClusterIP
 ports:
   - name: listen-endpoint
     protocol: TCP
     port: 7051

   - name: chaincode-listen
     protocol: TCP
     port: 7052

   - name: event-listen
     protocol: TCP
     port: 7053